# Generated by Django 6.0.6 on 2026-06-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='certification',
            field=models.FileField(blank=True, null=True, upload_to='certifications/'),
        ),
    ]
