# Generated by Django 6.0.6 on 2026-06-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorsapp', '0002_tutorprofile_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
