# Generated by Django 6.0.6 on 2026-06-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorsapp', '0004_rename_hourly_rate_tutorprofile_monthly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
