# Generated by Django 6.0.6 on 2026-07-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorsapp', '0005_tutorprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
