# Generated by Django 6.0.6 on 2026-07-13 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorsapp', '0008_tutorscheduleslot_booking_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorscheduleslot',
            name='batch_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutorscheduleslot',
            name='recurrence_type',
            field=models.CharField(choices=[('NONE', 'None'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='tutorscheduleslot',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutorsapp.subject'),
        ),
    ]
