# Generated by Django 6.0.6 on 2026-07-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorsapp', '0009_tutorscheduleslot_batch_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorscheduleslot',
            name='batch_label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
