# Generated by Django 6.0.6 on 2026-07-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorsapp', '0011_attendance_attendancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('PARTIAL', 'Partial'), ('ABSENT', 'Absent')], default='ABSENT', max_length=15),
        ),
    ]
