# Generated by Django 6.0.6 on 2026-07-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorsapp', '0013_alter_chatroom_unique_together_chatroom_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorscheduleslot',
            name='max_students',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tutorscheduleslot',
            name='session_type',
            field=models.CharField(choices=[('ONE_TO_ONE', 'One-to-One'), ('ONE_TO_MANY', 'One-to-Many')], default='ONE_TO_ONE', max_length=15),
        ),
    ]
