# Generated by Django 6.0.6 on 2026-07-21 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorsapp', '0016_assignment_assignmentsubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorprofile',
            old_name='monthly_rate',
            new_name='hourly_rate',
        ),
    ]
