# Generated by Django 6.0.6 on 2026-07-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorsapp', '0017_rename_monthly_rate_tutorprofile_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='intro_video',
            field=models.FileField(blank=True, null=True, upload_to='intro_videos/'),
        ),
    ]
