# Generated by Django 6.0.6 on 2026-07-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorsapp', '0020_remove_tutorprofile_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='subjects',
            field=models.ManyToManyField(related_name='tutors', through='tutorsapp.TutorSubject', to='tutorsapp.subject'),
        ),
    ]
