from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.course_list, name='list'),
    path('category/<int:category_id>/', views.category_detail, name='category_detail'),
    path('<int:course_id>/', views.course_detail, name='detail'),
    path('<int:course_id>/enroll/', views.enroll_course, name='enroll'),
    path('teacher/create/', views.teacher_create_course, name='teacher_create_course'),
    path('teacher/<int:course_id>/edit/', views.teacher_edit_course, name='teacher_edit_course'),
    path('teacher/<int:course_id>/manage/', views.teacher_manage_course, name='teacher_manage_course'),
    path('teacher/<int:course_id>/delete/', views.teacher_delete_course, name='teacher_delete_course'),
    path('teacher/<int:course_id>/add-content/', views.teacher_add_course_content, name='teacher_add_course_content'),
    path('live/<int:class_id>/', views.join_live_class, name='join_live_class'),
    path('live/room/<str:room_name>/', views.join_live_class_by_room, name='join_live_class_by_room'),
    path('app-login-redirect/', views.app_login_redirect, name='app_login_redirect'),
    path('live/<int:class_id>/save-board/', views.save_whiteboard, name='save_whiteboard'),
    path('live/<int:class_id>/get-board/', views.get_whiteboard, name='get_whiteboard'),
    path('live/<int:class_id>/end/', views.teacher_end_live_class, name='teacher_end_live_class'),
    path('live/<int:class_id>/summary/', views.post_class_summary, name='post_class_summary'),
    path('live/<int:class_id>/toggle-break/', views.toggle_live_class_break, name='toggle_live_class_break'),
    path('live/<int:class_id>/delete/', views.teacher_delete_live_class, name='teacher_delete_live_class'),
    path('live/<int:class_id>/upload-recording/', views.upload_recording_and_transcript, name='upload_recording_and_transcript'),
    path('recording/<int:rc_id>/toggle-visibility/', views.toggle_recording_visibility, name='toggle_recording_visibility'),
    path('recording/<int:rc_id>/delete/', views.delete_recorded_class, name='delete_recorded_class'),
    path('live/<int:class_id>/transcript-settings/', views.update_transcript_settings, name='update_transcript_settings'),
    path('live/<int:class_id>/transcript-delete/', views.delete_transcript, name='delete_transcript'),
    path('live/<int:class_id>/transcript/', views.view_class_transcript, name='view_class_transcript'),
    path('live/<int:class_id>/exit/', views.mark_attendance_exit, name='mark_attendance_exit'),
    path('student/submit-work/', views.student_submit_work, name='student_submit_work'),
    path('teacher/submissions/<str:item_type>/<int:item_id>/', views.teacher_view_submissions, name='teacher_view_submissions'),
    path('teacher/submissions/<int:submission_id>/grade/', views.teacher_grade_submission, name='teacher_grade_submission'),
    path('teacher/student/<int:student_id>/', views.teacher_student_detail, name='teacher_student_detail'),
    path('teacher/schedule/', views.teacher_schedule_view, name='teacher_schedule_view'),
    path('teacher/calendar/', views.teacher_calendar_view, name='teacher_calendar_view'),
    path('teacher/calendar/slots-list/', views.teacher_slots_list_view, name='teacher_slots_list'),
    path('api/slots/', views.api_get_teacher_slots, name='api_get_teacher_slots'),
    path('api/teacher/calendar-events/', views.api_teacher_calendar_events, name='api_teacher_calendar_events'),
    path('api/slots/manage/', views.api_manage_slot, name='api_manage_slot'),
    path('api/slots/book/', views.api_book_slot, name='api_book_slot'),
    path('api/slots/check-recurring/', views.api_check_recurring_slots, name='api_check_recurring_slots'),
    path('api/slots/cancel/', views.api_cancel_booking, name='api_cancel_booking'),
    path('parent/schedule/', views.parent_schedule_view, name='parent_schedule_view'),
    path('api/slots/bookable/<int:student_id>/', views.api_get_bookable_slots_for_student, name='api_get_bookable_slots_for_student'),
    path('live/translate/', views.translate_live_caption, name='translate_live_caption'),
    path('live/<int:class_id>/custom-whiteboard/', views.custom_whiteboard, name='custom_whiteboard'),
]
