# Generated by Django 6.1 on 2026-08-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='student',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='studynote',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studynote',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='tutorscheduleslot',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='tutorscheduleslot',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='AssignmentSubmission',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='AttendanceLog',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='StudyNote',
        ),
        migrations.DeleteModel(
            name='TutorScheduleSlot',
        ),
    ]
