# Generated by Django 6.1 on 2026-08-18 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('tutorsapp', '0002_remove_assignmentsubmission_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='tutorsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_details', to='courses.category'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='subjects',
            field=models.ManyToManyField(related_name='tutors', through='tutorsapp.TutorSubject', to='courses.category'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
