# Generated by Django 6.1 on 2026-08-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorsapp', '0003_remove_tutorprofile_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsubject',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
