# Generated by Django 6.1 on 2026-08-17 11:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Final Price set by Admin', max_digits=10)),
                ('teacher_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price requested by Teacher', max_digits=10)),
                ('features', models.TextField(blank=True, help_text='Enter features separated by newlines', null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/')),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='course_intro_videos/')),
                ('skills', models.TextField(blank=True, help_text='Skills taught in this course', null=True)),
                ('about_teaching', models.TextField(blank=True, help_text='About your teaching style', null=True)),
                ('experience', models.TextField(blank=True, help_text='Experience relevant to this course', null=True)),
                ('hourly_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Hourly fee per student', max_digits=10)),
                ('admin_hourly_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Final hourly fee for teacher set by Admin', max_digits=10)),
                ('total_duration_hours', models.IntegerField(default=0, help_text='Total duration in hours')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total Amount', max_digits=10)),
                ('is_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_comment', models.TextField(blank=True, help_text='Comments from Admin regarding approval, pricing, or rejection', null=True)),
                ('is_frozen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to_all', models.BooleanField(default=True)),
                ('assigned_students', models.ManyToManyField(blank=True, related_name='assigned_assignments', to='accounts.studentprofile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='course_notes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to_all', models.BooleanField(default=True)),
                ('assigned_students', models.ManyToManyField(blank=True, related_name='assigned_course_notes', to='accounts.studentprofile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Live Session', max_length=200)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('max_capacity', models.IntegerField(default=1)),
                ('is_ended', models.BooleanField(default=False)),
                ('room_name', models.CharField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True, help_text='Auto-generated class transcript', null=True)),
                ('ai_summary', models.TextField(blank=True, help_text='AI generated summary of the transcript', null=True)),
                ('transcript_visible', models.BooleanField(default=False)),
                ('transcript_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_on_break', models.BooleanField(default=False)),
                ('break_started_at', models.DateTimeField(blank=True, null=True)),
                ('class_type', models.CharField(choices=[('private', 'Private (1-to-1)'), ('public', 'Public (Group)')], default='private', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Final price for public class', max_digits=10)),
                ('teacher_requested_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Requested price by teacher', max_digits=10)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('recurring_group_id', models.CharField(blank=True, help_text='Groups recurring slots together', max_length=100, null=True)),
                ('is_free', models.BooleanField(default=False, help_text='True if this is a free/demo class')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSummaryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='class_notes/')),
                ('visibility', models.CharField(choices=[('teacher_only', 'Teacher Only (Private)'), ('parents_only', 'Parents Only'), ('students_only', 'Booked Students Only'), ('everyone', 'Everyone (Teacher, Parents, Students)')], default='everyone', max_length=20)),
                ('note_type', models.CharField(choices=[('regular', 'Study Material / Note'), ('complaint', 'Complaint / Issue')], default='regular', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_notes', to='courses.liveclass')),
            ],
        ),
        migrations.CreateModel(
            name='LiveClassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='confirmed', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='courses.liveclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_class_bookings', to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='projects/')),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to_all', models.BooleanField(default=True)),
                ('assigned_students', models.ManyToManyField(blank=True, related_name='assigned_projects', to='accounts.studentprofile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='RecordedClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='recorded_videos/')),
                ('attachment1', models.FileField(blank=True, null=True, upload_to='recorded_notes/')),
                ('attachment2', models.FileField(blank=True, null=True, upload_to='recorded_ppts/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_visible_to_students', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Time after which students can no longer view this recording', null=True)),
                ('assigned_to_all', models.BooleanField(default=True)),
                ('assigned_students', models.ManyToManyField(blank=True, related_name='assigned_recorded_classes', to='accounts.studentprofile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_classes', to='courses.course')),
                ('live_class', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recording', to='courses.liveclass')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted (Under Review)'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('resubmit', 'Needs Resubmission')], default='submitted', max_length=20)),
                ('teacher_comments', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.assignment')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WhiteboardState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_data', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whiteboard', to='courses.liveclass')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('selected_weekly_slots', models.JSONField(blank=True, default=list)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='absent', max_length=10)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.studentprofile')),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='courses.liveclass')),
            ],
            options={
                'unique_together': {('student', 'live_class')},
            },
        ),
    ]
