# Generated by Django 6.1 on 2026-08-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_liveclassbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='student_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
