# Generated by Django 6.1 on 2026-09-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_studentsubmission_student_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('partial', 'Partial')], default='absent', max_length=10),
        ),
    ]
